### ISSUE TITLE
Support request/worker queues

### ISSUE THREAD

**Issue by thinkh** [phovea/phovea_server#1]
**Current Status**
If one request take longer to process (e.g., database operation, clustering) all upcoming requests are pending, too. 

![long_requests](https://cloud.githubusercontent.com/assets/5851088/18205448/525027c4-7122-11e6-930e-068174f12643.PNG)

**Wanted**
All request or at least longer processes should be added to a queue and not block upcoming requests. A common library for that task is [Celery: Distributed Task Queue](http://www.celeryproject.org/). 

**Questions**
- Is there a response while the request is being processed? If yes, what will be returned and how would the processed response be returned to the client?
- Applications have to be aware that some results might come later. We have to check if promises will still work?

**Comment by thinkh** [comment]
The basic integration of Celery into Flask is described in the [Flask documentation](http://flask.pocoo.org/docs/0.11/patterns/celery/).

[This tutorial](http://blog.miguelgrinberg.com/post/using-celery-with-flask) uses a combination of Celery and Flask. The progress bar is updated by polling the backend periodically. The author extended this tutorial by using the [Flask Application Factory Pattern](http://blog.miguelgrinberg.com/post/celery-and-the-flask-application-factory-pattern)

**Comment by thinkh** [comment]
Please see the implementation in the new repository [caleydo_processing_queue](https://github.com/Caleydo/caleydo_processing_queue).

**Comment by sgratzl** [comment]
see also Caleydo/caleydo_web_container#82

**Comment by sgratzl** [comment]
not part of the core
