### ISSUE TITLE
JSON encoding of NaNs in Python not standards compliant

### ISSUE THREAD

**Issue by lehnerchristian** [phovea/phovea_server#107]
* Release number or git hash: 
* Web browser version and OS: 
* Environment (local or deployed): 

### Steps to reproduce

1. from any route in the backend try to `return jsonify(dict(myNum=float('nan)))`
2. call this route from any application
3. an error will be shown in the Browser console

### Observed behavior

Error message:
```
SyntaxError: "JSON.parse: unexpected character at line 1 column 9 of the JSON data"
```

### Expected behavior

returned JSON should be parsable by JSON.parse in the browser

## Reason for this

previously we used Pandas to encode JSON which deprecated and removed the JSON encoding feature. Pandas used to encode `NaN` as `null` according to [the docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_json.html)

From Panda's docs:
> Note NaN’s and None will be converted to null and datetime objects will be converted to UNIX timestamps.

we don't use Pandas anymore and replaced it with the standard JSON encoder. for NaN values the docs contain the following statement:

> If allow_nan is True (the default), then NaN, Infinity, and -Infinity will be encoded as such. This behavior is not JSON specification compliant, but is consistent with most JavaScript based encoders and decoders. Otherwise, it will be a ValueError to encode such floats.

however the `JSON.parse` cannot handle NaN values:

```
JSON.parse('{"a": NaN}') // Syntax error (see above)
```

On the other hand `JSON.stringify` correctly encodes `NaN` as `null`:

```
 JSON.stringify({"a": NaN})
```

### Possible Solution 1

Use the simplejson module: https://stackoverflow.com/questions/28639953/python-json-encoder-convert-nans-to-null-instead

### Possible Solution 2

**Attention:** an answer in the link in Possible Solution 1 states that this may not work, because the default method won't be called (see [this answer](https://stackoverflow.com/a/28640141/3527644))

A solution would be do register an `json-encoder` extension which is loaded by the `JSONExtensibleEncoder` class: https://github.com/phovea/phovea_server/blob/master/phovea_server/util.py#L12-L27

if we implement it similar to the `BytesToStringEncoder` (see https://github.com/datavisyn/tdp_core/blob/master/tdp_core/bytes_to_string_encoder.py#L7-L23) we could solve the issue.

* `__contains__` would then have to return true for NaN values (`import math and math.isnan(obj)`)
* `__call__` would have to convert the value to `null`

**Comment by thinkh** [comment]
Merged with PR #113 and released with v5.0.0
