### ISSUE TITLE
Update `last_deployment` API call to meet the Docker deployment

### ISSUE THREAD

**Issue by thinkh** [phovea/phovea_server#30]
Coming from https://github.com/phovea/phovea_ui/issues/6 the API call `http://localhost:8080/api/last_deployment/` should meet the new Docker deployment.

@sgratzl What file or data can I use to retrieve the last deployment timestamp?

**Comment by sgratzl** [comment]
a build info is generated and hosted that is way more informative, see https://github.com/phovea/phovea_ui/blob/develop/src/buildInfo.ts#L74

**Comment by thinkh** [comment]
Might be replace with the `./phoveaMetaData.json` that is created on the fly as part of the build process. (Hence, it's not available in a local installation.)

Content: https://github.com/Caleydo/lineup/blob/develop/buildInfo.js#L152

**Comment by sgratzl** [comment]
Hence, it's not available in a local installation
as with the `buildInfo.json` is it part of the build process = webpack -> you should have it locally but it is a derived file

**Comment by sgratzl** [comment]
removed and replaced with phoveaMetaData.json
