### ISSUE TITLE
Run phovea_server errors with `launch.py: error: argument cmd: invalid choice: 'api' (choose from )`

### ISSUE THREAD

**Issue by thinkh** [phovea/phovea_server#71]
* Release number or git hash: f75ef87ad9afaaa161c3c0afadd8adfdea04a561 (develop)
* Web browser version and OS: n/a
* Environment (local or deployed): AWS

### Steps to reproduce

1. Build ordino product with CircleCI
2. Two images (ordino + ordino_server) are pushed to AWS
3. Create task definition for Ordino containing (web, api, mongo, redis)
4. Run task definition -> result: task is running
5. Open subdomain in browser -> result: task is stopped

### Observed behavior

The logs of the `api` container from the task definition show the following error:

```
usage: launch.py [-h] [--use_reloader] [--env ENV] {} ...
launch.py: error: argument cmd: invalid choice: 'api' (choose from )
configuration file: /phovea_config/config.json
```

### Expected behavior

* The task should run and not stop

### Additional information

I had a discussion with @anita-steiner about the same error on the 28.08.2018. At that time there were some changes in generator-phovea. The generator could not handle `-` in python if it was a workspace package. This bug should be fixed with https://github.com/phovea/generator-phovea/commit/f7dd142be4a68b4c25007fa03a3686ab3a1cc330 and https://github.com/phovea/generator-phovea/commit/5cd08de497f5784c2b81d35e966216524c34d317. According to @anita-steiner I had to rebuild the product without cache in CircleCI. This way CircleCI retrieves the most recent generator and the Docker image was/is working correctly.

However, following this tip, I rebuild the Ordino product without cache, but the error described above remains. The generated Docker image is still wrong.

**Comment by lehnerchristian** [comment]
try another version of the phovea generator: https://github.com/phovea/generator-phovea/commits/sgratzl/mergeWorkspace

so you'll need to copy this dependency: `"generator-phovea": "github:phovea/generator-phovea#b4e238879d78a9f006a03312319594b367f4efb2"` to your product's `package.json` file

I had the same error today. @sgratzl gave me this hint. this fixed it for me

**Comment by thinkh** [comment]
@lehnerchristian Thanks for the hint. I will try.

**Comment by thinkh** [comment]
@lehnerchristian It works, thanks. 👍
