### ISSUE TITLE
Switch Docker base images for Python 3.7 in deploy Dockerfile

### ISSUE THREAD

**Issue by thinkh** [phovea/phovea_server#92]
Switch Docker base images from `caleydo/phovea_python:v1.1` to `python:3.7`:

https://github.com/phovea/phovea_server/blob/5b7e9a8cb32667640110f6d1326115efc9a458cb/deploy/Dockerfile_dev#L1

https://github.com/phovea/phovea_server/blob/5b7e9a8cb32667640110f6d1326115efc9a458cb/deploy/Dockerfile#L1

Changes might be also necessary in product repos.

**Comment by dvvanessastoiber** [comment]
The Docker base images are already correct in the deploy Dockerfiles of the `develop` branches.
